### ISSUE TITLE
Getting error from implementation

### ISSUE THREAD

**Issue by codewithdripzy** [XeroDays/live_currency_rate#1]
Good day, i currently have an issue on this package
This is the code
`CurrencyRate rate =
        await LiveCurrencyRate.convertCurrency("USD", "NGN", total);

    print(rate.message);` 
    
   result is `flutter: Not Authorized. Return with Reponse code : 403
flutter: 0`

**Comment by XeroDays** [comment]
Hi, Thanks for informing, i will fix this in 48 Hours.

**Comment by codewithdripzy** [comment]
Alright Thanks

**Comment by XeroDays** [comment]
@codewithdripzy  Can you check now if it works? i have fixed the api

**Comment by codewithdripzy** [comment]
Alright thanks, I’ll check it nowSent from my iPhoneOn Feb 21, 2024, at 17:02, Sayed Muhammad Idrees ***@***.***> wrote:﻿
@codewithdripzy  Can you check now if it works? i have fixed the api

**Comment by codewithdripzy** [comment]
Still the same issues here
![61912EAB-2661-4D02-8C99-C7C770841227_4_5005_c](https://github.com/XeroDays/live_currency_rate/assets/102001454/ec6d64f6-6264-40eb-b103-0ecb3cdb3ffd)

**Comment by XeroDays** [comment]
Will Check from the Flutter Side ASAP.
Standby.

**Comment by codewithdripzy** [comment]
Ok, thanks. Let me know the update ASAP

**Comment by XeroDays** [comment]
[Fixed] Thank you for noticing and forwarding the issue to us. we have fixed both API and FrontEnd Flutter code, you can now install the new version 1.0.4 or run the example project. 
please let us know if the issue still stands. 
Thank you

**Comment by codewithdripzy** [comment]
Thank you for your help, I'll check now

**Comment by codewithdripzy** [comment]
Yeah, thank you it works now
